// Comprehensive list of country codes with flags and country names
export const countryCodes = [
    { id: "af", code: "+93", flag: "🇦🇫", country: "Afghanistan" },
    { id: "al", code: "+355", flag: "🇦🇱", country: "Albania" },
    { id: "dz", code: "+213", flag: "🇩🇿", country: "Algeria" },
    { id: "as", code: "+1", flag: "🇦🇸", country: "American Samoa" },
    { id: "ad", code: "+376", flag: "🇦🇩", country: "Andorra" },
    { id: "ao", code: "+244", flag: "🇦🇴", country: "Angola" },
    { id: "ai", code: "+1", flag: "🇦🇮", country: "Anguilla" },
    { id: "aq", code: "+672", flag: "🇦🇶", country: "Antarctica" },
    { id: "ag", code: "+1", flag: "🇦🇬", country: "Antigua and Barbuda" },
    { id: "ar", code: "+54", flag: "🇦🇷", country: "Argentina" },
    { id: "am", code: "+374", flag: "🇦🇲", country: "Armenia" },
    { id: "aw", code: "+297", flag: "🇦🇼", country: "Aruba" },
    { id: "au", code: "+61", flag: "🇦🇺", country: "Australia" },
    { id: "at", code: "+43", flag: "🇦🇹", country: "Austria" },
    { id: "az", code: "+994", flag: "🇦🇿", country: "Azerbaijan" },
    { id: "bs", code: "+1", flag: "🇧🇸", country: "Bahamas" },
    { id: "bh", code: "+973", flag: "🇧🇭", country: "Bahrain" },
    { id: "bd", code: "+880", flag: "🇧🇩", country: "Bangladesh" },
    { id: "bb", code: "+1", flag: "🇧🇧", country: "Barbados" },
    { id: "by", code: "+375", flag: "🇧🇾", country: "Belarus" },
    { id: "be", code: "+32", flag: "🇧🇪", country: "Belgium" },
    { id: "bz", code: "+501", flag: "🇧🇿", country: "Belize" },
    { id: "bj", code: "+229", flag: "🇧🇯", country: "Benin" },
    { id: "bm", code: "+1", flag: "🇧🇲", country: "Bermuda" },
    { id: "bt", code: "+975", flag: "🇧🇹", country: "Bhutan" },
    { id: "bo", code: "+591", flag: "🇧🇴", country: "Bolivia" },
    { id: "ba", code: "+387", flag: "🇧🇦", country: "Bosnia and Herzegovina" },
    { id: "bw", code: "+267", flag: "🇧🇼", country: "Botswana" },
    { id: "br", code: "+55", flag: "🇧🇷", country: "Brazil" },
    { id: "io", code: "+246", flag: "🇮🇴", country: "British Indian Ocean Territory" },
    { id: "vg", code: "+1", flag: "🇻🇬", country: "British Virgin Islands" },
    { id: "bn", code: "+673", flag: "🇧🇳", country: "Brunei" },
    { id: "bg", code: "+359", flag: "🇧🇬", country: "Bulgaria" },
    { id: "bf", code: "+226", flag: "🇧🇫", country: "Burkina Faso" },
    { id: "bi", code: "+257", flag: "🇧🇮", country: "Burundi" },
    { id: "kh", code: "+855", flag: "🇰🇭", country: "Cambodia" },
    { id: "cm", code: "+237", flag: "🇨🇲", country: "Cameroon" },
    { id: "ca", code: "+1", flag: "🇨🇦", country: "Canada" },
    { id: "cv", code: "+238", flag: "🇨🇻", country: "Cape Verde" },
    { id: "ky", code: "+1", flag: "🇰🇾", country: "Cayman Islands" },
    { id: "cf", code: "+236", flag: "🇨🇫", country: "Central African Republic" },
    { id: "td", code: "+235", flag: "🇹🇩", country: "Chad" },
    { id: "cl", code: "+56", flag: "🇨🇱", country: "Chile" },
    { id: "cn", code: "+86", flag: "🇨🇳", country: "China" },
    { id: "cx", code: "+61", flag: "🇨🇽", country: "Christmas Island" },
    { id: "cc", code: "+61", flag: "🇨🇨", country: "Cocos Islands" },
    { id: "co", code: "+57", flag: "🇨🇴", country: "Colombia" },
    { id: "km", code: "+269", flag: "🇰🇲", country: "Comoros" },
    { id: "ck", code: "+682", flag: "🇨🇰", country: "Cook Islands" },
    { id: "cr", code: "+506", flag: "🇨🇷", country: "Costa Rica" },
    { id: "hr", code: "+385", flag: "🇭🇷", country: "Croatia" },
    { id: "cu", code: "+53", flag: "🇨🇺", country: "Cuba" },
    { id: "cw", code: "+599", flag: "🇨🇼", country: "Curacao" },
    { id: "cy", code: "+357", flag: "🇨🇾", country: "Cyprus" },
    { id: "cz", code: "+420", flag: "🇨🇿", country: "Czech Republic" },
    { id: "cd", code: "+243", flag: "🇨🇩", country: "Democratic Republic of the Congo" },
    { id: "dk", code: "+45", flag: "🇩🇰", country: "Denmark" },
    { id: "dj", code: "+253", flag: "🇩🇯", country: "Djibouti" },
    { id: "dm", code: "+1", flag: "🇩🇲", country: "Dominica" },
    { id: "do", code: "+1", flag: "🇩🇴", country: "Dominican Republic" },
    { id: "tl", code: "+670", flag: "🇹🇱", country: "East Timor" },
    { id: "ec", code: "+593", flag: "🇪🇨", country: "Ecuador" },
    { id: "eg", code: "+20", flag: "🇪🇬", country: "Egypt" },
    { id: "sv", code: "+503", flag: "🇸🇻", country: "El Salvador" },
    { id: "gq", code: "+240", flag: "🇬🇶", country: "Equatorial Guinea" },
    { id: "er", code: "+291", flag: "🇪🇷", country: "Eritrea" },
    { id: "ee", code: "+372", flag: "🇪🇪", country: "Estonia" },
    { id: "et", code: "+251", flag: "🇪🇹", country: "Ethiopia" },
    { id: "fk", code: "+500", flag: "🇫🇰", country: "Falkland Islands" },
    { id: "fo", code: "+298", flag: "🇫🇴", country: "Faroe Islands" },
    { id: "fj", code: "+679", flag: "🇫🇯", country: "Fiji" },
    { id: "fi", code: "+358", flag: "🇫🇮", country: "Finland" },
    { id: "fr", code: "+33", flag: "🇫🇷", country: "France" },
    { id: "pf", code: "+689", flag: "🇵🇫", country: "French Polynesia" },
    { id: "ga", code: "+241", flag: "🇬🇦", country: "Gabon" },
    { id: "gm", code: "+220", flag: "🇬🇲", country: "Gambia" },
    { id: "ge", code: "+995", flag: "🇬🇪", country: "Georgia" },
    { id: "de", code: "+49", flag: "🇩🇪", country: "Germany" },
    { id: "gh", code: "+233", flag: "🇬🇭", country: "Ghana" },
    { id: "gi", code: "+350", flag: "🇬🇮", country: "Gibraltar" },
    { id: "gr", code: "+30", flag: "🇬🇷", country: "Greece" },
    { id: "gl", code: "+299", flag: "🇬🇱", country: "Greenland" },
    { id: "gd", code: "+1", flag: "🇬🇩", country: "Grenada" },
    { id: "gu", code: "+1", flag: "🇬🇺", country: "Guam" },
    { id: "gt", code: "+502", flag: "🇬🇹", country: "Guatemala" },
    { id: "gg", code: "+44", flag: "🇬🇬", country: "Guernsey" },
    { id: "gn", code: "+224", flag: "🇬🇳", country: "Guinea" },
    { id: "gw", code: "+245", flag: "🇬🇼", country: "Guinea-Bissau" },
    { id: "gy", code: "+592", flag: "🇬🇾", country: "Guyana" },
    { id: "ht", code: "+509", flag: "🇭🇹", country: "Haiti" },
    { id: "hn", code: "+504", flag: "🇭🇳", country: "Honduras" },
    { id: "hk", code: "+852", flag: "🇭🇰", country: "Hong Kong" },
    { id: "hu", code: "+36", flag: "🇭🇺", country: "Hungary" },
    { id: "is", code: "+354", flag: "🇮🇸", country: "Iceland" },
    { id: "in", code: "+91", flag: "🇮🇳", country: "India" },
    { id: "id", code: "+62", flag: "🇮🇩", country: "Indonesia" },
    { id: "ir", code: "+98", flag: "🇮🇷", country: "Iran" },
    { id: "iq", code: "+964", flag: "🇮🇶", country: "Iraq" },
    { id: "ie", code: "+353", flag: "🇮🇪", country: "Ireland" },
    { id: "im", code: "+44", flag: "🇮🇲", country: "Isle of Man" },
    { id: "il", code: "+972", flag: "🇮🇱", country: "Israel" },
    { id: "it", code: "+39", flag: "🇮🇹", country: "Italy" },
    { id: "ci", code: "+225", flag: "🇨🇮", country: "Ivory Coast" },
    { id: "jm", code: "+1", flag: "🇯🇲", country: "Jamaica" },
    { id: "jp", code: "+81", flag: "🇯🇵", country: "Japan" },
    { id: "je", code: "+44", flag: "🇯🇪", country: "Jersey" },
    { id: "jo", code: "+962", flag: "🇯🇴", country: "Jordan" },
    { id: "kz", code: "+7", flag: "🇰🇿", country: "Kazakhstan" },
    { id: "ke", code: "+254", flag: "🇰🇪", country: "Kenya" },
    { id: "ki", code: "+686", flag: "🇰🇮", country: "Kiribati" },
    { id: "xk", code: "+383", flag: "🇽🇰", country: "Kosovo" },
    { id: "kw", code: "+965", flag: "🇰🇼", country: "Kuwait" },
    { id: "kg", code: "+996", flag: "🇰🇬", country: "Kyrgyzstan" },
    { id: "la", code: "+856", flag: "🇱🇦", country: "Laos" },
    { id: "lv", code: "+371", flag: "🇱🇻", country: "Latvia" },
    { id: "lb", code: "+961", flag: "🇱🇧", country: "Lebanon" },
    { id: "ls", code: "+266", flag: "🇱🇸", country: "Lesotho" },
    { id: "lr", code: "+231", flag: "🇱🇷", country: "Liberia" },
    { id: "ly", code: "+218", flag: "🇱🇾", country: "Libya" },
    { id: "li", code: "+423", flag: "🇱🇮", country: "Liechtenstein" },
    { id: "lt", code: "+370", flag: "🇱🇹", country: "Lithuania" },
    { id: "lu", code: "+352", flag: "🇱🇺", country: "Luxembourg" },
    { id: "mo", code: "+853", flag: "🇲🇴", country: "Macau" },
    { id: "mk", code: "+389", flag: "🇲🇰", country: "Macedonia" },
    { id: "mg", code: "+261", flag: "🇲🇬", country: "Madagascar" },
    { id: "mw", code: "+265", flag: "🇲🇼", country: "Malawi" },
    { id: "my", code: "+60", flag: "🇲🇾", country: "Malaysia" },
    { id: "mv", code: "+960", flag: "🇲🇻", country: "Maldives" },
    { id: "ml", code: "+223", flag: "🇲🇱", country: "Mali" },
    { id: "mt", code: "+356", flag: "🇲🇹", country: "Malta" },
    { id: "mh", code: "+692", flag: "🇲🇭", country: "Marshall Islands" },
    { id: "mr", code: "+222", flag: "🇲🇷", country: "Mauritania" },
    { id: "mu", code: "+230", flag: "🇲🇺", country: "Mauritius" },
    { id: "yt", code: "+262", flag: "🇾🇹", country: "Mayotte" },
    { id: "mx", code: "+52", flag: "🇲🇽", country: "Mexico" },
    { id: "fm", code: "+691", flag: "🇫🇲", country: "Micronesia" },
    { id: "md", code: "+373", flag: "🇲🇩", country: "Moldova" },
    { id: "mc", code: "+377", flag: "🇲🇨", country: "Monaco" },
    { id: "mn", code: "+976", flag: "🇲🇳", country: "Mongolia" },
    { id: "me", code: "+382", flag: "🇲🇪", country: "Montenegro" },
    { id: "ms", code: "+1", flag: "🇲🇸", country: "Montserrat" },
    { id: "ma", code: "+212", flag: "🇲🇦", country: "Morocco" },
    { id: "mz", code: "+258", flag: "🇲🇿", country: "Mozambique" },
    { id: "mm", code: "+95", flag: "🇲🇲", country: "Myanmar" },
    { id: "na", code: "+264", flag: "🇳🇦", country: "Namibia" },
    { id: "nr", code: "+674", flag: "🇳🇷", country: "Nauru" },
    { id: "np", code: "+977", flag: "🇳🇵", country: "Nepal" },
    { id: "nl", code: "+31", flag: "🇳🇱", country: "Netherlands" },
    { id: "nc", code: "+687", flag: "🇳🇨", country: "New Caledonia" },
    { id: "nz", code: "+64", flag: "🇳🇿", country: "New Zealand" },
    { id: "ni", code: "+505", flag: "🇳🇮", country: "Nicaragua" },
    { id: "ne", code: "+227", flag: "🇳🇪", country: "Niger" },
    { id: "ng", code: "+234", flag: "🇳🇬", country: "Nigeria" },
    { id: "nu", code: "+683", flag: "🇳🇺", country: "Niue" },
    { id: "kp", code: "+850", flag: "🇰🇵", country: "North Korea" },
    { id: "mp", code: "+1", flag: "🇲🇵", country: "Northern Mariana Islands" },
    { id: "no", code: "+47", flag: "🇳🇴", country: "Norway" },
    { id: "om", code: "+968", flag: "🇴🇲", country: "Oman" },
    { id: "pk", code: "+92", flag: "🇵🇰", country: "Pakistan" },
    { id: "pw", code: "+680", flag: "🇵🇼", country: "Palau" },
    { id: "ps", code: "+970", flag: "🇵🇸", country: "Palestine" },
    { id: "pa", code: "+507", flag: "🇵🇦", country: "Panama" },
    { id: "pg", code: "+675", flag: "🇵🇬", country: "Papua New Guinea" },
    { id: "py", code: "+595", flag: "🇵🇾", country: "Paraguay" },
    { id: "pe", code: "+51", flag: "🇵🇪", country: "Peru" },
    { id: "ph", code: "+63", flag: "🇵🇭", country: "Philippines" },
    { id: "pn", code: "+64", flag: "🇵🇳", country: "Pitcairn" },
    { id: "pl", code: "+48", flag: "🇵🇱", country: "Poland" },
    { id: "pt", code: "+351", flag: "🇵🇹", country: "Portugal" },
    { id: "pr", code: "+1", flag: "🇵🇷", country: "Puerto Rico" },
    { id: "qa", code: "+974", flag: "🇶🇦", country: "Qatar" },
    { id: "cg", code: "+242", flag: "🇨🇬", country: "Republic of the Congo" },
    { id: "re", code: "+262", flag: "🇷🇪", country: "Reunion" },
    { id: "ro", code: "+40", flag: "🇷🇴", country: "Romania" },
    { id: "ru", code: "+7", flag: "🇷🇺", country: "Russia" },
    { id: "rw", code: "+250", flag: "🇷🇼", country: "Rwanda" },
    { id: "bl", code: "+590", flag: "🇧🇱", country: "Saint Barthelemy" },
    { id: "sh", code: "+290", flag: "🇸🇭", country: "Saint Helena" },
    { id: "kn", code: "+1", flag: "🇰🇳", country: "Saint Kitts and Nevis" },
    { id: "lc", code: "+1", flag: "🇱🇨", country: "Saint Lucia" },
    { id: "mf", code: "+590", flag: "🇲🇫", country: "Saint Martin" },
    { id: "pm", code: "+508", flag: "🇵🇲", country: "Saint Pierre and Miquelon" },
    { id: "vc", code: "+1", flag: "🇻🇨", country: "Saint Vincent and the Grenadines" },
    { id: "ws", code: "+685", flag: "🇼🇸", country: "Samoa" },
    { id: "sm", code: "+378", flag: "🇸🇲", country: "San Marino" },
    { id: "st", code: "+239", flag: "🇸🇹", country: "Sao Tome and Principe" },
    { id: "sa", code: "+966", flag: "🇸🇦", country: "Saudi Arabia" },
    { id: "sn", code: "+221", flag: "🇸🇳", country: "Senegal" },
    { id: "rs", code: "+381", flag: "🇷🇸", country: "Serbia" },
    { id: "sc", code: "+248", flag: "🇸🇨", country: "Seychelles" },
    { id: "sl", code: "+232", flag: "🇸🇱", country: "Sierra Leone" },
    { id: "sg", code: "+65", flag: "🇸🇬", country: "Singapore" },
    { id: "sx", code: "+1", flag: "🇸🇽", country: "Sint Maarten" },
    { id: "sk", code: "+421", flag: "🇸🇰", country: "Slovakia" },
    { id: "si", code: "+386", flag: "🇸🇮", country: "Slovenia" },
    { id: "sb", code: "+677", flag: "🇸🇧", country: "Solomon Islands" },
    { id: "so", code: "+252", flag: "🇸🇴", country: "Somalia" },
    { id: "za", code: "+27", flag: "🇿🇦", country: "South Africa" },
    { id: "kr", code: "+82", flag: "🇰🇷", country: "South Korea" },
    { id: "ss", code: "+211", flag: "🇸🇸", country: "South Sudan" },
    { id: "es", code: "+34", flag: "🇪🇸", country: "Spain" },
    { id: "lk", code: "+94", flag: "🇱🇰", country: "Sri Lanka" },
    { id: "sd", code: "+249", flag: "🇸🇩", country: "Sudan" },
    { id: "sr", code: "+597", flag: "🇸🇷", country: "Suriname" },
    { id: "sj", code: "+47", flag: "🇸🇯", country: "Svalbard and Jan Mayen" },
    { id: "sz", code: "+268", flag: "🇸🇿", country: "Swaziland" },
    { id: "se", code: "+46", flag: "🇸🇪", country: "Sweden" },
    { id: "ch", code: "+41", flag: "🇨🇭", country: "Switzerland" },
    { id: "sy", code: "+963", flag: "🇸🇾", country: "Syria" },
    { id: "tw", code: "+886", flag: "🇹🇼", country: "Taiwan" },
    { id: "tj", code: "+992", flag: "🇹🇯", country: "Tajikistan" },
    { id: "tz", code: "+255", flag: "🇹🇿", country: "Tanzania" },
    { id: "th", code: "+66", flag: "🇹🇭", country: "Thailand" },
    { id: "tg", code: "+228", flag: "🇹🇬", country: "Togo" },
    { id: "tk", code: "+690", flag: "🇹🇰", country: "Tokelau" },
    { id: "to", code: "+676", flag: "🇹🇴", country: "Tonga" },
    { id: "tt", code: "+1", flag: "🇹🇹", country: "Trinidad and Tobago" },
    { id: "tn", code: "+216", flag: "🇹🇳", country: "Tunisia" },
    { id: "tr", code: "+90", flag: "🇹🇷", country: "Turkey" },
    { id: "tm", code: "+993", flag: "🇹🇲", country: "Turkmenistan" },
    { id: "tc", code: "+1", flag: "🇹🇨", country: "Turks and Caicos Islands" },
    { id: "tv", code: "+688", flag: "🇹🇻", country: "Tuvalu" },
    { id: "vi", code: "+1", flag: "🇻🇮", country: "U.S. Virgin Islands" },
    { id: "ug", code: "+256", flag: "🇺🇬", country: "Uganda" },
    { id: "ua", code: "+380", flag: "🇺🇦", country: "Ukraine" },
    { id: "ae", code: "+971", flag: "🇦🇪", country: "United Arab Emirates" },
    { id: "gb", code: "+44", flag: "🇬🇧", country: "United Kingdom" },
    { id: "us", code: "+1", flag: "🇺🇸", country: "United States" },
    { id: "uy", code: "+598", flag: "🇺🇾", country: "Uruguay" },
    { id: "uz", code: "+998", flag: "🇺🇿", country: "Uzbekistan" },
    { id: "vu", code: "+678", flag: "🇻🇺", country: "Vanuatu" },
    { id: "va", code: "+379", flag: "🇻🇦", country: "Vatican" },
    { id: "ve", code: "+58", flag: "🇻🇪", country: "Venezuela" },
    { id: "vn", code: "+84", flag: "🇻🇳", country: "Vietnam" },
    { id: "wf", code: "+681", flag: "🇼🇫", country: "Wallis and Futuna" },
    { id: "eh", code: "+212", flag: "🇪🇭", country: "Western Sahara" },
    { id: "ye", code: "+967", flag: "🇾🇪", country: "Yemen" },
    { id: "zm", code: "+260", flag: "🇿🇲", country: "Zambia" },
    { id: "zw", code: "+263", flag: "🇿🇼", country: "Zimbabwe" }
];
